// <auto-generated />
using System;
using BackendFinal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackendFinal.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackendFinal.Admin", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("BackendFinal.Appointment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<int>("DonatorID")
                        .HasColumnType("int");

                    b.Property<int>("timeslot")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("DoctorID");

                    b.HasIndex("DonatorID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("BackendFinal.Doctor", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("CNP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("BackendFinal.Donator", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("BloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Donators");
                });

            modelBuilder.Entity("BackendFinal.Location", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("BackendFinal.User_Working", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userType")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackendFinal.Admin", b =>
                {
                    b.HasOne("BackendFinal.User_Working", null)
                        .WithOne("A")
                        .HasForeignKey("BackendFinal.Admin", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendFinal.Appointment", b =>
                {
                    b.HasOne("BackendFinal.Doctor", null)
                        .WithMany("App")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackendFinal.Donator", null)
                        .WithMany("App")
                        .HasForeignKey("DonatorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendFinal.Doctor", b =>
                {
                    b.HasOne("BackendFinal.User_Working", null)
                        .WithOne("D")
                        .HasForeignKey("BackendFinal.Doctor", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendFinal.Donator", b =>
                {
                    b.HasOne("BackendFinal.User_Working", null)
                        .WithOne("DD")
                        .HasForeignKey("BackendFinal.Donator", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendFinal.Doctor", b =>
                {
                    b.Navigation("App");
                });

            modelBuilder.Entity("BackendFinal.Donator", b =>
                {
                    b.Navigation("App");
                });

            modelBuilder.Entity("BackendFinal.User_Working", b =>
                {
                    b.Navigation("A");

                    b.Navigation("D");

                    b.Navigation("DD");
                });
#pragma warning restore 612, 618
        }
    }
}
